source 'https://rubygems.org'

gem 'mongoid'
gem 'faraday'
gem 'nokogiri'
gem 'byebug'
gem "faraday-detailed_logger"
gem 'dotenv'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'slim'
gem 'shotgun'
gem 'link_header'
gem 'travis'
gem 'ansi-to-html'
gem 'childprocess'
gem 'puma'
gem 'taw', git: 'https://github.com/AlexMooney/taw', branch: 'approx_taaw_method'
