source 'https://rubygems.org'

# Dogfood
#gem 'mongo', git: 'https://github.com/mongodb/mongo-ruby-driver'
#gem 'mongoid', git: 'https://github.com/mongodb/mongoid'
gem 'mongo'
gem 'mongoid'

gem 'faraday'
gem 'nokogiri'
gem 'byebug'
gem "faraday-detailed_logger"
gem 'dotenv'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'slim'
gem 'shotgun'
gem 'link_header'
gem 'travis'
gem 'ansi-to-html'
gem 'childprocess'
gem 'puma'
gem 'taw'
gem 'sidekiq'
gem 'sidekiq-cron'
gem 'jira-ruby'
gem 'htmlentities'
gem 'actionpack'
