#!/bin/sh

set -e

rm -rf dist
mkdir dist dist/static
#./node_modules/.bin/webpack --config webpack.config.prod.js -p --env.API_URL='"'$API_URL'"'
./node_modules/.bin/webpack --config webpack.config.prod.js -p --env.API_URL='"'/api'"'
cp build/* dist/static
cp index.html dist
rsync -a public/ dist
