#!/usr/bin/env ruby

$: << File.join(File.dirname(File.realpath(__FILE__)), '../lib')

ENV['MONGOID_ENV'] = 'development'

require 'fe/boot_lite'
require 'fe/env'

project_name = ARGV.shift or raise "Need project name"
project = Env.eg_client.project_by_id(project_name)
puts YAML.dump(project.vars)
