#!/usr/bin/env ruby

$: << File.join(File.dirname(__FILE__), '../lib')

ENV['MONGOID_ENV'] = 'development'

require 'fe/boot_lite'
require 'fe/patch_build_maker'
require 'optparse'

options = {}
OptionParser.new do |opts|
  opts.on('-b', '--base=BASE', 'Specify base branch') do |v|
    options[:base_branch] = v
  end
  opts.on('-p', '--project=PROJECT', 'Evergreen project to patch into') do |v|
    options[:eg_project_id] = v
  end
  opts.on('-f', '--force', 'Force submission') do |v|
    options[:force] = true
  end
end.parse!

PatchBuildMaker.new.run(**options)
