#!/usr/bin/env ruby

$: << File.join(File.dirname(__FILE__), '../lib')

ENV['MONGOID_ENV'] = 'development'

require 'fe/boot_lite'
require 'pr_maker'

what = ARGV.shift
if what.nil?
  pr_maker = CurrentPrMaker.new
else
  num = what.to_i
  if num > 0
    pr_maker = TicketedPrMaker.new(num)
  else
    pr_maker = BranchPrMaker.new(what)
  end
end
pr_maker.make_pr
