#!/usr/bin/env ruby

$: << File.join(File.dirname(__FILE__), '../lib')

ENV['MONGOID_ENV'] = 'development'

require 'evergreen/parser_validator'
require 'fe/boot_lite'
require 'fe/env'

path = ARGV.shift
unless path
  raise "Usage: validate-eg-config path"
end

begin
  Evergreen::ParserValidator.new(File.read(path)).validate!
rescue Evergreen::ProjectFileInvalid => e
  puts e.to_s
  exit 1
end
